### ISSUE TITLE
how is this code run?

### ISSUE THREAD

**Issue by zkievanlou** [AdiShirsath/Neural-Machine-Translation#1]
Hi
Your article looks very interesting. I want to run your code. If possible, guide me to run your code.
Thank you in advance

**Comment by AdiShirsath** [comment]
Sure it will be easier to run in google colab . Take any .ipynb file and try to run it. and if you want to understand any code why I used it u can follow medium blog (link in readme). And if need any help feel free to contact me :)

**Comment by zkievanlou** [comment]
thank you  so much
Could you Please guide me in detail how to run this code in Google colab (train and translation)?
