### ISSUE TITLE
local attention model

### ISSUE THREAD

**Issue by zkievanlou** [AdiShirsath/Neural-Machine-Translation#2]
Hi
Your paper"English-Marathi Neural Machine Translation Using Local Attention" looks very interesting. Could you  please tell me if this code implements local attention for machine translation? 
Thank you in advance

**Comment by AdiShirsath** [comment]
Yes. I have used Bahdanau’s attention. in Attention dir you can find one python file which has code for attention. now we simply import that file and put attention on our encoder-decode model. 

Link for bahdnau's attention paper- https://medium.com/geekculture/neural-machine-translation-using-seq2seq-model-with-attention-9faea357d70b

**Comment by AdiShirsath** [comment]
pls follow this blog- https://medium.com/geekculture/neural-machine-translation-using-seq2seq-model-with-attention-9faea357d70b
it will be easier to understand all stuff. I have also provided links to learn all prerequisite in this and if you get stuck somewhere in blog feel free to contact me

**Comment by zkievanlou** [comment]
Thank you very much for your help. But I still do not know exactly what
kind of attention you have used. In this article"english-marathi neural
machine translation using local attention " you have used the title Local
Attention. But what is stated in the blog is the model of this
article"NEURAL MACHINE TRANSLATIONBY JOINTLY LEARNING TO ALIGN AND
TRANSLATE", which does not have the title of local attention. But I mean
the local attention introduced in this article" Effective Approaches to
Attention-based Neural Machine Translation".
I am a student and for my project I need to implement local attention for
Masini translation. The content of your blog is very useful to me May I
have two requests from you? First, could you please send me your full
article? Second, could you  please explain to me how to run your code in
more detail(command  instruction)?
best regards
